Repository GSG-G13/Ecommerce-team8, pull requests merged in 2023-03, with the labels that each got.

#2 Initializing the project
  .gitignore
  cart/cart.css
  cart/cart.html
  cart/cart.js
  index.html
  package-lock.json
  package.json
  script/main.js
  seller/seller.css
  seller/seller.html
  seller/seller.js
  styles/style.css
Labels: in-Progress

#8 Home page css
  .vscode/settings.json
  imges/1.jpg
  imges/2.jpg
  imges/2955_6.jpg
  imges/3.jpg
  imges/4.jpg
  imges/5.jpg
  index.html
  styles/style.css
Labels: approved

#6 created html home page
  index.html
Labels: in-Progress

#9 create seller html structure
  seller/seller.html
Labels: in-Progress

#11 add slider js
  script/main.js
Labels: approved

#17 style the seller.css
  seller/seller.css
  seller/seller.html
Labels: approved

#16 adding seller.js
  seller/seller.html
  seller/seller.js
Labels: waiting for review

#21 render product seller
  seller/seller.js
Labels: approved

#23 add render function to home page
  index.html
  script/main.js
Labels: approved

#26 recreate seller pahe
  seller/seller.css
  seller/seller.html
  seller/seller.js
Labels: approved

#28 add to cart function is added
  script/main.js
Labels: approved

#31 new-html-css-homepage-updates
  index.html
  seller/seller.html
  styles/style.css
Labels: waiting for review

#35 home-page-new-edits-html-css-js
  index.html
  script/main.js
  styles/style.css
Labels: approved

#36 change few thing in js
  seller/seller.js
Labels: waiting for review

#39 js filter by price filter
  index.html
  script/main.js
Labels: approved

#40 updating seller.htmk seller.js
  seller/seller.html
  seller/seller.js
Labels: approved

#42 add the cart functions
  cart/cart.html
  cart/cart.js
Labels: waiting for review

#43 js filter by category
  index.html
  script/main.js
Labels: waiting for review

#47 change something
  cart/cart.html
  cart/cart.js
  seller/seller.js
Labels: waiting for review

#51 add test dir and test js
  __test__/test.js
  seller/helper.js
  seller/seller.html
  seller/seller.js
Labels: waiting for review

#55 test filter by price
  __test__/test.js
  index.html
  package.json
  script/main.js
  seller/helper.js
Labels: waiting for review

#56 52 adding a test to filter function
  __test__/test.js
  script/main.js
  seller/helper.js
Labels: waiting for review
